### ISSUE TITLE
동아리 목록 페이지 작업

### ISSUE THREAD

**Issue by kimdev0206** [SYULION8TH/2020-syu-club-client#15]

**Comment by YOOGOMJA** [comment]
동아리 목록 디자인 파일을 확인해서 작업해주세요 

- [x] 디자인 구현하기
- [x] 목록 API 가져오기
- [x] 검색 구현

## 작업 폴더 

`views/ClubListView`

**Comment by blair06** [comment]
[PostSearch component사용방법]
postSearch component의 input의 value를 state에 저장하여 부모컴포넌트의 state를 변경하여 사용합니다.

부모컴포넌트에 const[values, setValues] = useState('');를  작성하고 postSearch component를 불러와 props로 setValues = {setValues} values={values}를 지정해주세요 (PostListView index파일 참고)
api를 적절하게 수정해주세요 (posts.api의 getPosts를 참고)
*직접적인 css수정은 하지 말아주세요
div를 이용하거나 props로 className을 받아 적절하게 수정해주세요
** 추가적인 문의는 연락해주세요
